// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TicketMasterVFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketMasterVFinal.Aplicacao.Modelos.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<DateTime?>("ultima_atualizacao_cadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_atualizacao_cadastro");

                    b.HasKey("Id");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("TicketMasterVFinal.Aplicacao.Modelos.Tickets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("funcionarioID")
                        .HasColumnType("integer")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<DateTime?>("ultima_atualizacao_cadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.HasKey("id");

                    b.HasIndex("funcionarioID");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("TicketMasterVFinal.Aplicacao.Modelos.Tickets", b =>
                {
                    b.HasOne("TicketMasterVFinal.Aplicacao.Modelos.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
